name: Deploy app
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - name: build app
        run: npm run build
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: ${{ secrets.USERNAME }}
            server: ${{ secrets.SERVER }}
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
            local_path: './out/*'
            remote_path: '/home/brassagemforte/www/associacoes'